"""Tests for the S3 storage backend.

Requests are checked with botocore's Stubber, so nothing reaches the network.
Presigned URLs are generated by a real client with fake credentials, which is
also offline.
"""

import io
from unittest.mock import MagicMock
from urllib.parse import parse_qs, urlparse

import pytest

from feather.exceptions import StorageError

boto3 = pytest.importorskip("boto3")
from botocore.stub import Stubber  # noqa: E402

from feather.storage.s3 import MissingS3Dependency, S3Storage  # noqa: E402

pytestmark = pytest.mark.integration

ENDPOINT = "http://s3.test:3900"


def make_storage(**kwargs):
    options = dict(
        bucket_name="uploads",
        endpoint_url=ENDPOINT,
        region="garage",
        access_key_id="GKtest",
        secret_access_key="secret",
    )
    options.update(kwargs)
    return S3Storage(**options)


@pytest.fixture
def storage():
    return make_storage()


@pytest.fixture
def stub(storage):
    with Stubber(storage.client) as stubber:
        yield stubber
        stubber.assert_no_pending_responses()


def not_found(stubber, method="head_object"):
    stubber.add_client_error(method, service_error_code="404" if method == "head_object" else "NoSuchKey",
                             http_status_code=404)


# =============================================================================
# Client configuration
# =============================================================================


class TestClientConfiguration:
    def test_custom_endpoint_uses_path_style_and_relaxed_checksums(self, storage):
        config = storage.client.meta.config
        assert storage.addressing_style == "path"
        assert config.s3["addressing_style"] == "path"
        assert config.request_checksum_calculation == "when_required"
        assert config.response_checksum_validation == "when_required"
        assert storage.client.meta.endpoint_url == ENDPOINT
        assert storage.client.meta.region_name == "garage"

    def test_aws_defaults_to_auto_and_keeps_boto_checksum_defaults(self):
        storage = S3Storage("uploads", region="eu-central-1",
                            access_key_id="AK", secret_access_key="SK")
        config = storage.client.meta.config
        assert storage.addressing_style == "auto"
        assert config.request_checksum_calculation != "when_required"

    def test_explicit_addressing_style_wins(self):
        storage = make_storage(addressing_style="virtual")
        assert storage.client.meta.config.s3["addressing_style"] == "virtual"

    def test_invalid_addressing_style_is_refused(self):
        with pytest.raises(StorageError, match="S3_ADDRESSING_STYLE"):
            make_storage(addressing_style="sideways")

    def test_half_a_credential_pair_is_refused(self):
        with pytest.raises(StorageError, match="S3_SECRET_ACCESS_KEY"):
            make_storage(secret_access_key=None)

    def test_missing_credentials_fall_back_to_the_boto3_chain(self, monkeypatch):
        monkeypatch.setenv("AWS_ACCESS_KEY_ID", "from-env")
        monkeypatch.setenv("AWS_SECRET_ACCESS_KEY", "from-env-secret")
        storage = make_storage(access_key_id=None, secret_access_key=None)
        assert storage.client._request_signer._credentials.access_key == "from-env"

    def test_bucket_is_required(self):
        with pytest.raises(StorageError, match="S3_BUCKET"):
            S3Storage("")

    def test_bad_url_expires_is_refused(self):
        with pytest.raises(StorageError, match="S3_URL_EXPIRES"):
            make_storage(url_expires="soon")

    def test_missing_boto3_names_the_extra(self):
        from tests.unit.test_optional_deps import hide_module

        with hide_module("boto3"), pytest.raises(MissingS3Dependency) as exc:
            S3Storage("uploads")
        message = str(exc.value)
        assert "pip install 'feather-framework[s3]'" in message
        assert isinstance(exc.value, ImportError)
        assert isinstance(exc.value, StorageError)


# =============================================================================
# Keys and extensions
# =============================================================================


class TestKeySafety:
    @pytest.mark.parametrize(
        "key",
        ["", "   ", "/etc/passwd", "a/../b.txt", "../b.txt", "a/./b.txt", "a//b.txt",
         "dir/", "a\\b.txt", "C:/x.txt", "bad\nname.txt", "bad\x00.txt"],
    )
    def test_unsafe_keys_are_refused_before_any_request(self, storage, key):
        storage.client = MagicMock()
        with pytest.raises(StorageError, match="Invalid storage path"):
            storage.upload(b"x", key)
        with pytest.raises(StorageError, match="Invalid storage path"):
            storage.exists(key)
        storage.client.put_object.assert_not_called()
        storage.client.head_object.assert_not_called()

    def test_overlong_key_is_refused(self, storage):
        with pytest.raises(StorageError, match="1024"):
            storage.exists("a" * 1025)

    @pytest.mark.parametrize("name", ["page.html", "x.SVG", "app.js", "a.php"])
    def test_script_capable_extensions_are_blocked(self, storage, name):
        storage.client = MagicMock()
        with pytest.raises(StorageError, match="blocked"):
            storage.upload(b"x", f"uploads/{name}")
        storage.client.put_object.assert_not_called()

    def test_allow_list_wins(self):
        storage = make_storage(allowed_extensions="png, .svg")
        storage.client = MagicMock()
        storage.client.generate_presigned_url.return_value = "https://signed"
        storage.upload(b"<svg/>", "logo.svg")
        with pytest.raises(StorageError, match="not allowed"):
            storage.upload(b"x", "notes.txt")

    def test_block_list_can_be_replaced(self):
        storage = make_storage(blocked_extensions="exe")
        storage.client = MagicMock()
        storage.client.generate_presigned_url.return_value = "https://signed"
        storage.upload(b"<svg/>", "logo.svg")
        with pytest.raises(StorageError, match="blocked"):
            storage.upload(b"x", "setup.exe")


# =============================================================================
# Operations
# =============================================================================


class TestOperations:
    def test_upload_bytes_puts_the_object_and_returns_a_presigned_url(self, storage, stub):
        stub.add_response(
            "put_object",
            {},
            {"Bucket": "uploads", "Key": "avatars/42.png", "Body": b"png", "ContentType": "image/png"},
        )
        url = storage.upload(b"png", "avatars/42.png")

        parsed = urlparse(url)
        assert f"{parsed.scheme}://{parsed.netloc}" == ENDPOINT
        assert parsed.path == "/uploads/avatars/42.png"  # path style
        query = parse_qs(parsed.query)
        assert query["X-Amz-Expires"] == ["3600"]
        assert "X-Amz-Signature" in query

    def test_upload_file_object_and_path(self, storage, tmp_path):
        storage.client = MagicMock()
        storage.client.generate_presigned_url.return_value = "https://signed"

        buffer = io.BytesIO(b"data")
        assert storage.upload(buffer, "docs/a.pdf") == "https://signed"
        storage.client.upload_fileobj.assert_called_once_with(
            buffer, "uploads", "docs/a.pdf", ExtraArgs={"ContentType": "application/pdf"}
        )

        source = tmp_path / "b.txt"
        source.write_text("hi")
        storage.upload(source, "docs/b.txt", content_type="text/plain")
        storage.client.upload_file.assert_called_once_with(
            str(source), "uploads", "docs/b.txt", ExtraArgs={"ContentType": "text/plain"}
        )

        with pytest.raises(StorageError, match="Source file not found"):
            storage.upload(tmp_path / "missing.txt", "docs/c.txt")

    def test_upload_failure_is_a_storage_error(self, storage, stub):
        stub.add_client_error("put_object", service_error_code="AccessDenied", http_status_code=403)
        with pytest.raises(StorageError, match="Failed to upload to S3"):
            storage.upload(b"x", "a.txt")

    def test_download(self, storage, stub):
        from botocore.response import StreamingBody

        body = StreamingBody(io.BytesIO(b"contents"), len(b"contents"))
        stub.add_response("get_object", {"Body": body}, {"Bucket": "uploads", "Key": "a.txt"})
        assert storage.download("a.txt") == b"contents"

    def test_download_missing_file(self, storage, stub):
        not_found(stub, "get_object")
        with pytest.raises(StorageError, match="File not found in S3"):
            storage.download("missing.txt")

    def test_exists(self, storage, stub):
        stub.add_response("head_object", {}, {"Bucket": "uploads", "Key": "a.txt"})
        not_found(stub)
        assert storage.exists("a.txt") is True
        assert storage.exists("b.txt") is False

    def test_exists_does_not_hide_access_errors(self, storage, stub):
        stub.add_client_error("head_object", service_error_code="403", http_status_code=403)
        with pytest.raises(StorageError, match="Failed to check S3 object"):
            storage.exists("a.txt")

    def test_delete(self, storage, stub):
        stub.add_response("head_object", {}, {"Bucket": "uploads", "Key": "a.txt"})
        stub.add_response("delete_object", {}, {"Bucket": "uploads", "Key": "a.txt"})
        not_found(stub)
        assert storage.delete("a.txt") is True
        assert storage.delete("a.txt") is False

    def test_get_url_presigns_with_options(self, storage, stub):
        stub.add_response("head_object", {}, {"Bucket": "uploads", "Key": "r/report.pdf"})
        url = storage.get_url("r/report.pdf", expires_in=60, download_name='Q3 "final".pdf',
                              content_type="application/pdf")
        query = parse_qs(urlparse(url).query)
        assert query["X-Amz-Expires"] == ["60"]
        assert query["response-content-disposition"] == ['inline; filename="Q3 final.pdf"']
        assert query["response-content-type"] == ["application/pdf"]

    def test_get_url_default_expiry_from_setting(self):
        storage = make_storage(url_expires="120")
        with Stubber(storage.client) as stubber:
            stubber.add_response("head_object", {}, {"Bucket": "uploads", "Key": "a.txt"})
            url = storage.get_url("a.txt")
        assert parse_qs(urlparse(url).query)["X-Amz-Expires"] == ["120"]

    def test_get_url_missing_file(self, storage, stub):
        not_found(stub)
        with pytest.raises(StorageError, match="File not found in S3"):
            storage.get_url("missing.txt")

    def test_public_url_skips_signing(self):
        storage = make_storage(public_url="https://cdn.example.com/")
        with Stubber(storage.client) as stubber:
            stubber.add_response("put_object", {}, None)
            stubber.add_response("head_object", {}, None)
            assert storage.upload(b"x", "a b/c.png") == "https://cdn.example.com/a%20b/c.png"
            assert storage.get_url("a b/c.png") == "https://cdn.example.com/a%20b/c.png"


# =============================================================================
# get_storage
# =============================================================================


class TestGetStorage:
    S3_KEYS = ("STORAGE_BACKEND", "S3_BUCKET", "S3_ENDPOINT", "S3_REGION", "S3_ACCESS_KEY_ID",
               "S3_SECRET_ACCESS_KEY", "S3_ADDRESSING_STYLE", "S3_URL_EXPIRES", "S3_PUBLIC_URL")

    @pytest.fixture(autouse=True)
    def clean_env(self, monkeypatch):
        for key in self.S3_KEYS:
            monkeypatch.delenv(key, raising=False)

    def test_env_injected_s3_settings_build_an_s3_backend(self, monkeypatch):
        from tests.conftest import feather_app
        from feather.storage import get_storage

        monkeypatch.setenv("S3_BUCKET", "app-files")
        monkeypatch.setenv("S3_ENDPOINT", ENDPOINT)
        monkeypatch.setenv("S3_REGION", "garage")
        monkeypatch.setenv("S3_ACCESS_KEY_ID", "GKtest")
        monkeypatch.setenv("S3_SECRET_ACCESS_KEY", "secret")
        monkeypatch.setenv("S3_URL_EXPIRES", "900")

        with feather_app() as app, app.app_context():
            storage = get_storage()

        assert isinstance(storage, S3Storage)
        assert storage.bucket_name == "app-files"
        assert storage.addressing_style == "path"
        assert storage.url_expires == 900

    def test_app_config_wins_over_env(self, monkeypatch):
        from tests.conftest import feather_app
        from feather.storage import get_storage

        monkeypatch.setenv("S3_BUCKET", "from-env")
        with feather_app(S3_BUCKET="from-config", S3_ACCESS_KEY_ID="a",
                         S3_SECRET_ACCESS_KEY="b", S3_REGION="us-east-1") as app:
            storage = get_storage(app)
        assert storage.bucket_name == "from-config"

    def test_explicit_s3_without_bucket_is_an_error(self):
        from tests.conftest import feather_app
        from feather.storage import get_storage

        with feather_app(STORAGE_BACKEND="s3") as app:
            with pytest.raises(StorageError, match="S3_BUCKET is required"):
                get_storage(app)

    def test_explicit_local_wins_over_s3_bucket(self, monkeypatch):
        from tests.conftest import feather_app
        from feather.storage import get_storage
        from feather.storage.local import LocalStorage

        monkeypatch.setenv("S3_BUCKET", "app-files")
        with feather_app(STORAGE_BACKEND="local") as app:
            assert isinstance(get_storage(app), LocalStorage)
