"""Autogenerated migrations create circular foreign keys after the tables.

SQLAlchemy leaves a use_alter key out of CREATE TABLE, so a key rendered
inside op.create_table was never created, and the next autogenerate added it.
"""

import pytest
import sqlalchemy as sa
from alembic.autogenerate import produce_migrations, render_python_code
from alembic.migration import MigrationContext

from feather.db.migrations import defer_circular_foreign_keys

pytestmark = pytest.mark.unit


def circular_metadata():
    metadata = sa.MetaData()
    sa.Table(
        "users", metadata,
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "account_id", sa.String(36),
            sa.ForeignKey("accounts.id", use_alter=True, name="fk_users_account_id"),
        ),
    )
    sa.Table(
        "accounts", metadata,
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("owner_id", sa.String(36), sa.ForeignKey("users.id")),
    )
    return metadata


def script_for(metadata):
    engine = sa.create_engine("sqlite://")
    with engine.connect() as connection:
        context = MigrationContext.configure(connection)
        return produce_migrations(context, metadata)


def test_use_alter_key_moves_out_of_create_table():
    script = script_for(circular_metadata())
    defer_circular_foreign_keys(None, None, [script])
    upgrade = render_python_code(script.upgrade_ops)

    create_users = upgrade[upgrade.index("create_table('users'"):]
    create_users = create_users[: create_users.index(")\n    op.") + 1] if ")\n    op." in create_users else create_users
    assert "fk_users_account_id" not in create_users
    assert "op.create_foreign_key('fk_users_account_id', 'users', 'accounts', ['account_id'], ['id']" in upgrade
    # After both tables exist.
    assert upgrade.index("create_foreign_key") > upgrade.rindex("create_table(")


def test_ordinary_keys_stay_inline():
    script = script_for(circular_metadata())
    defer_circular_foreign_keys(None, None, [script])
    upgrade = render_python_code(script.upgrade_ops)
    assert "sa.ForeignKeyConstraint(['owner_id'], ['users.id'], )" in upgrade
    assert upgrade.count("create_foreign_key") == 1


def test_downgrade_drops_the_key_before_the_tables():
    script = script_for(circular_metadata())
    defer_circular_foreign_keys(None, None, [script])
    downgrade = render_python_code(script.downgrade_ops)
    assert downgrade.index("drop_constraint('fk_users_account_id', 'users', type_='foreignkey')") < downgrade.index("drop_table(")


def test_nothing_to_defer_leaves_the_script_alone():
    metadata = sa.MetaData()
    sa.Table("notes", metadata, sa.Column("id", sa.Integer, primary_key=True))
    script = script_for(metadata)
    before = render_python_code(script.upgrade_ops)
    defer_circular_foreign_keys(None, None, [script])
    assert render_python_code(script.upgrade_ops) == before
    defer_circular_foreign_keys(None, None, [])  # no directives: no error


def test_sqlite_is_left_alone():
    """SQLite cannot ALTER a constraint in, so its migration keeps the key inline."""
    engine = sa.create_engine("sqlite://")
    with engine.connect() as connection:
        context = MigrationContext.configure(connection)
        script = produce_migrations(context, circular_metadata())
        before = render_python_code(script.upgrade_ops)
        defer_circular_foreign_keys(context, None, [script])
    assert render_python_code(script.upgrade_ops) == before
    assert "create_foreign_key" not in before
